// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCudzkO1gkZmAn5YkE740lqQu80izGPww',
    appId: '1:506703120708:web:d5bd964fcc90d73ed3af11',
    messagingSenderId: '506703120708',
    projectId: 'swim-application-22a16',
    authDomain: 'swim-application-22a16.firebaseapp.com',
    storageBucket: 'swim-application-22a16.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBaWTL_wR2tWrQIGauefkmqTO5To0lfKNw',
    appId: '1:506703120708:android:c6e135272f89ea35d3af11',
    messagingSenderId: '506703120708',
    projectId: 'swim-application-22a16',
    storageBucket: 'swim-application-22a16.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJF0dxdiTjLTh1Rd5SKPzcE9Dmax-s_9c',
    appId: '1:506703120708:ios:a1cd738f9233c373d3af11',
    messagingSenderId: '506703120708',
    projectId: 'swim-application-22a16',
    storageBucket: 'swim-application-22a16.appspot.com',
    iosClientId:
        '506703120708-rlojob5gin9pqp3gbt1ou7dm5fouvb96.apps.googleusercontent.com',
    iosBundleId: 'com.example.swimApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJF0dxdiTjLTh1Rd5SKPzcE9Dmax-s_9c',
    appId: '1:506703120708:ios:a882c05c9be56870d3af11',
    messagingSenderId: '506703120708',
    projectId: 'swim-application-22a16',
    storageBucket: 'swim-application-22a16.appspot.com',
    iosClientId:
        '506703120708-0b8k32rvrchdsgu2f1mv12loo2a937fi.apps.googleusercontent.com',
    iosBundleId: 'com.example.swimApplication.RunnerTests',
  );
}
